apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: lv-tensor
  labels:
    app: lv-tensor
spec:
  replicas: 1
  selector:
    app: lv-tensor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lv-tensor
    spec:
      containers:
      - name: lv-transformer-container
        image: image-registry.openshift-image-registry.svc:5000/oswaldoriosz-dev/lv-tensor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: ENV
          value: "production"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: lv-tensor-configmap
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - lv-tensor-container
      from:
        kind: ImageStreamTag
        name: lv-tensor:latest
